Return-Path: <user@domain.com.br>
Received: from mx.serverdomain.com.br (mx.serverdomain.com.br [192.0.2.19])
	by mail.serverdomain.com.br with ESMTP id AB83000
	for <user@domain.com.br>; Fri, 12 Sep 2025 20:15:45 -0300 (-03)
Received: from srv1-2.serverdomain.com.br (srv1-2.serverdomain.com.br [192.0.2.23])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange x25519 server-signature RSA-PSS (2048 bits) server-digest SHA256)
	(No client certificate requested)
	by mx.serverdomain.com.br with ESMTPS id AB04F9FB00
	for <user@domain.com.br>; Fri, 12 Sep 2025 20:15:45 -0300 (-03)
Received: from srv1.serverdomain.com.br (localhost [127.0.0.1])
	by srv1.serverdomain.com.br with ESMTP id ABE9E1C0000
	for <user@domain.com.br>; Fri, 12 Sep 2025 20:15:45 -0300 (-03)
Received: from localhost.localdomain (unknown [192.0.2.250])
	(Authenticated sender: user@domain.com.br)
	by srv1.serverdomain.com.br with ESMTP id ABC221C0100
	for <user@domain.com.br>; Fri, 12 Sep 2025 20:15:43 -0300 (-03)
From: user@domain.com.br
To: user@domain.com.br
Message-ID: <f0e54312-6303-4e0e-b166-58a8a7d06474@domain.com.br>
Content-Type: multipart/mixed;
	boundary="----=_Part_0_1712189221.1757718944881"
Subject: subject
Date: Fri, 12 Sep 2025 20:15:43 -0300 (-03)
ARC-Authentication-Results: prev
ARC-Message-Signature: prev
ARC-Seal: prev
MIME-Version: 1.0

------=_Part_0_1712189221.1757718944881
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html><body>example<br>example html<body></html>

------=_Part_0_1712189221.1757718944881
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

--
example
disclaimer
example...
------=_Part_0_1712189221.1757718944881--
